<a href="https://colab.research.google.com/github/Osesa1/Python-Data-Analysis-for-Healthcare-A-Learning-Journey/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# create a numpy array

arr1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [ ]:
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr2 = np.array((2,4,6))

In [ ]:
print(arr2)

[2 4 6]


In [ ]:
# python list different than numpy array

list1 = [2,4,6]
arr3 = np.array([2,4,6])

In [ ]:
print('the list is: ', list1)
print('the numpy array is: ', arr3)

the list is:  [2, 4, 6]
the numpy array is:  [2 4 6]


In [ ]:
print(list1*2)
print(arr3*2)

[2, 4, 6, 2, 4, 6]
[ 4  8 12]


In [ ]:
print(list1*3)
print(arr3*3)

[2, 4, 6, 2, 4, 6, 2, 4, 6]
[ 6 12 18]


In [ ]:
# create a numpy array using a range
arr4 =np.arange(1,11)
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# create a numpy array using zeros properties
# zeros takes 1 argument, so (())

zero = np.zeros((5,5))
print(zero)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
once = np.ones((6,4))
print(once)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# create full properties

full = np.full((6,6),3)
print(full)

[[3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]
 [3 3 3 3 3 3]]


In [ ]:
#identity matrix
# (3) = 3 by 3 with all ones

ide = np.eye(3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
iden = np.eye(5)
print(iden)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
num1 = np.array([[10,4],[11,16]])
print(num1)

[[10  4]
 [11 16]]


In [ ]:
# how to select
# (row, column)

print (num1[0,1])

4


In [ ]:
print (num1[1,0])

11


In [ ]:
num1.shape

(2, 2)